import { Eye, Grid3X3, Layers, List } from "lucide-react";
import type { CalendarEvent } from "@/types/calendar";

export const defaultSampleEvents: CalendarEvent[] = [
	// Past completed events for streak calculation
	{
		id: "past-1",
		date: new Date(2024, 11, 26),
		title: "Memory Enhancement Module",
		description: "Working memory and recall exercises",
		time: "9:00 AM",
		duration: "1 hour",
		type: "assessment",
		priority: "medium",
		color: "blue",
		status: "completed",
		score: 78,
		maxScore: 100,
		completedAt: new Date(2024, 11, 26, 10, 0),
	},
	{
		id: "past-2",
		date: new Date(2024, 11, 28),
		title: "Critical Reasoning Test",
		description: "Evaluate logical reasoning and decision-making skills",
		time: "10:00 AM",
		duration: "2 hours",
		type: "assessment",
		priority: "high",
		color: "blue",
		status: "completed",
		score: 85,
		maxScore: 100,
		previousScore: 78,
		improvementTrend: "up",
		completedAt: new Date(2024, 11, 28, 12, 0),
	},
	{
		id: "past-3",
		date: new Date(2025, 0, 3),
		title: "Pattern Recognition - Session 1",
		description: "Visual and logical pattern identification",
		time: "2:00 PM",
		duration: "45 minutes",
		type: "assessment",
		priority: "medium",
		color: "green",
		status: "completed",
		score: 92,
		maxScore: 100,
		sessionNumber: 1,
		totalSessions: 4,
		seriesId: "pattern-series-1",
		completedAt: new Date(2025, 0, 3, 14, 45),
	},
	// Upcoming events
	{
		id: "1",
		date: new Date(2025, 0, 8),
		title: "Pattern Recognition - Session 2",
		description: "Visual and logical pattern identification",
		time: "2:00 PM",
		duration: "45 minutes",
		type: "assessment",
		priority: "medium",
		color: "green",
		status: "scheduled",
		sessionNumber: 2,
		totalSessions: 4,
		seriesId: "pattern-series-1",
		previousScore: 92,
	},
	{
		id: "2",
		date: new Date(2025, 0, 9),
		title: "Working Memory Assessment",
		description: "Test cognitive flexibility and memory capacity",
		time: "2:00 PM",
		duration: "1.5 hours",
		type: "assessment",
		priority: "medium",
		color: "blue",
		status: "scheduled",
		previousScore: 85,
	},
	{
		id: "3",
		date: new Date(2025, 0, 17),
		title: "Bias Recognition Test",
		description: "Identify and mitigate cognitive biases",
		time: "11:00 AM",
		duration: "1 hour",
		type: "exam",
		priority: "high",
		color: "red",
		status: "scheduled",
	},
	{
		id: "4",
		date: new Date(2025, 0, 23),
		title: "Risk Assessment",
		description: "Evaluate risk assessment capabilities",
		time: "2:00 PM",
		duration: "3 hours",
		type: "assessment",
		priority: "medium",
		color: "purple",
		status: "scheduled",
	},
];

export const colorClasses = {
	blue: "bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200",
	green: "bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200",
	red: "bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200",
	yellow:
		"bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200",
	purple:
		"bg-purple-100 text-purple-800 dark:bg-purple-900 dark:text-purple-200",
};

export const colorDots = {
	blue: "bg-blue-500",
	green: "bg-green-500",
	red: "bg-red-500",
	yellow: "bg-yellow-500",
	purple: "bg-purple-500",
};

export const viewModeConfig = {
	compact: { icon: Grid3X3, label: "Compact" },
	stacked: { icon: Layers, label: "Stacked" },
	details: { icon: Eye, label: "Details" },
	list: { icon: List, label: "List" },
};