export const COUNTRIES = [
	{
		code: "AF",
		name: "Afghanistan",
		phoneCode: "+93",
		language: "Pashto, Dari",
	},
	{ code: "AL", name: "Albania", phoneCode: "+355", language: "Albanian" },
	{ code: "DZ", name: "Algeria", phoneCode: "+213", language: "Arabic" },
	{
		code: "AS",
		name: "American Samoa",
		phoneCode: "+1-684",
		language: "English, Samoan",
	},
	{ code: "AD", name: "Andorra", phoneCode: "+376", language: "Catalan" },
	{ code: "AO", name: "Angola", phoneCode: "+244", language: "Portuguese" },
	{ code: "AI", name: "Anguilla", phoneCode: "+1-264", language: "English" },
	{ code: "AQ", name: "Antarctica", phoneCode: "+672", language: "Various" },
	{
		code: "AG",
		name: "Antigua and Barbuda",
		phoneCode: "+1-268",
		language: "English",
	},
	{ code: "AR", name: "Argentina", phoneCode: "+54", language: "Spanish" },
	{ code: "AM", name: "Armenia", phoneCode: "+374", language: "Armenian" },
	{
		code: "AW",
		name: "Aruba",
		phoneCode: "+297",
		language: "Dutch, Papiamento",
	},
	{ code: "AU", name: "Australia", phoneCode: "+61", language: "English" },
	{ code: "AT", name: "Austria", phoneCode: "+43", language: "German" },
	{
		code: "AZ",
		name: "Azerbaijan",
		phoneCode: "+994",
		language: "Azerbaijani",
	},
	{ code: "BS", name: "Bahamas", phoneCode: "+1-242", language: "English" },
	{ code: "BH", name: "Bahrain", phoneCode: "+973", language: "Arabic" },
	{ code: "BD", name: "Bangladesh", phoneCode: "+880", language: "Bengali" },
	{ code: "BB", name: "Barbados", phoneCode: "+1-246", language: "English" },
	{
		code: "BY",
		name: "Belarus",
		phoneCode: "+375",
		language: "Belarusian, Russian",
	},
	{
		code: "BE",
		name: "Belgium",
		phoneCode: "+32",
		language: "Dutch, French, German",
	},
	{ code: "BZ", name: "Belize", phoneCode: "+501", language: "English" },
	{ code: "BJ", name: "Benin", phoneCode: "+229", language: "French" },
	{ code: "BM", name: "Bermuda", phoneCode: "+1-441", language: "English" },
	{ code: "BT", name: "Bhutan", phoneCode: "+975", language: "Dzongkha" },
	{
		code: "BO",
		name: "Bolivia, Plurinational State of",
		phoneCode: "+591",
		language: "Spanish, Quechua, Aymara",
	},
	{
		code: "BQ",
		name: "Bonaire, Sint Eustatius and Saba",
		phoneCode: "+599",
		language: "Dutch, Papiamento",
	},
	{
		code: "BA",
		name: "Bosnia and Herzegovina",
		phoneCode: "+387",
		language: "Bosnian, Croatian, Serbian",
	},
	{
		code: "BW",
		name: "Botswana",
		phoneCode: "+267",
		language: "English, Tswana",
	},
	{
		code: "BV",
		name: "Bouvet Island",
		phoneCode: "+47",
		language: "Norwegian",
	},
	{ code: "BR", name: "Brazil", phoneCode: "+55", language: "Portuguese" },
	{
		code: "IO",
		name: "British Indian Ocean Territory",
		phoneCode: "+246",
		language: "English",
	},
	{
		code: "BN",
		name: "Brunei Darussalam",
		phoneCode: "+673",
		language: "Malay",
	},
	{ code: "BG", name: "Bulgaria", phoneCode: "+359", language: "Bulgarian" },
	{ code: "BF", name: "Burkina Faso", phoneCode: "+226", language: "French" },
	{
		code: "BI",
		name: "Burundi",
		phoneCode: "+257",
		language: "Kirundi, French",
	},
	{ code: "CV", name: "Cabo Verde", phoneCode: "+238", language: "Portuguese" },
	{ code: "KH", name: "Cambodia", phoneCode: "+855", language: "Khmer" },
	{
		code: "CM",
		name: "Cameroon",
		phoneCode: "+237",
		language: "French, English",
	},
	{ code: "CA", name: "Canada", phoneCode: "+1", language: "English, French" },
	{
		code: "KY",
		name: "Cayman Islands",
		phoneCode: "+1-345",
		language: "English",
	},
	{
		code: "CF",
		name: "Central African Republic",
		phoneCode: "+236",
		language: "French, Sango",
	},
	{ code: "TD", name: "Chad", phoneCode: "+235", language: "French, Arabic" },
	{ code: "CL", name: "Chile", phoneCode: "+56", language: "Spanish" },
	{ code: "CN", name: "China", phoneCode: "+86", language: "Mandarin Chinese" },
	{
		code: "CX",
		name: "Christmas Island",
		phoneCode: "+61",
		language: "English",
	},
	{
		code: "CC",
		name: "Cocos (Keeling) Islands",
		phoneCode: "+61",
		language: "English",
	},
	{ code: "CO", name: "Colombia", phoneCode: "+57", language: "Spanish" },
	{
		code: "KM",
		name: "Comoros",
		phoneCode: "+269",
		language: "Comorian, French, Arabic",
	},
	{ code: "CG", name: "Congo", phoneCode: "+242", language: "French" },
	{
		code: "CD",
		name: "Congo, The Democratic Republic of the",
		phoneCode: "+243",
		language: "French",
	},
	{
		code: "CK",
		name: "Cook Islands",
		phoneCode: "+682",
		language: "English, Cook Islands Māori",
	},
	{ code: "CR", name: "Costa Rica", phoneCode: "+506", language: "Spanish" },
	{ code: "HR", name: "Croatia", phoneCode: "+385", language: "Croatian" },
	{ code: "CU", name: "Cuba", phoneCode: "+53", language: "Spanish" },
	{
		code: "CW",
		name: "Curaçao",
		phoneCode: "+599",
		language: "Dutch, Papiamento",
	},
	{ code: "CY", name: "Cyprus", phoneCode: "+357", language: "Greek, Turkish" },
	{ code: "CZ", name: "Czechia", phoneCode: "+420", language: "Czech" },
	{ code: "CI", name: "Côte d'Ivoire", phoneCode: "+225", language: "French" },
	{ code: "DK", name: "Denmark", phoneCode: "+45", language: "Danish" },
	{
		code: "DJ",
		name: "Djibouti",
		phoneCode: "+253",
		language: "French, Arabic",
	},
	{ code: "DM", name: "Dominica", phoneCode: "+1-767", language: "English" },
	{
		code: "DO",
		name: "Dominican Republic",
		phoneCode: "+1-809",
		language: "Spanish",
	},
	{ code: "EC", name: "Ecuador", phoneCode: "+593", language: "Spanish" },
	{ code: "EG", name: "Egypt", phoneCode: "+20", language: "Arabic" },
	{ code: "SV", name: "El Salvador", phoneCode: "+503", language: "Spanish" },
	{
		code: "GQ",
		name: "Equatorial Guinea",
		phoneCode: "+240",
		language: "Spanish, French, Portuguese",
	},
	{
		code: "ER",
		name: "Eritrea",
		phoneCode: "+291",
		language: "Tigrinya, Arabic",
	},
	{ code: "EE", name: "Estonia", phoneCode: "+372", language: "Estonian" },
	{
		code: "SZ",
		name: "Eswatini",
		phoneCode: "+268",
		language: "English, Swati",
	},
	{ code: "ET", name: "Ethiopia", phoneCode: "+251", language: "Amharic" },
	{
		code: "FK",
		name: "Falkland Islands (Malvinas)",
		phoneCode: "+500",
		language: "English",
	},
	{ code: "FO", name: "Faroe Islands", phoneCode: "+298", language: "Faroese" },
	{
		code: "FJ",
		name: "Fiji",
		phoneCode: "+679",
		language: "English, Fijian, Hindi",
	},
	{
		code: "FI",
		name: "Finland",
		phoneCode: "+358",
		language: "Finnish, Swedish",
	},
	{ code: "FR", name: "France", phoneCode: "+33", language: "French" },
	{ code: "GF", name: "French Guiana", phoneCode: "+594", language: "French" },
	{
		code: "PF",
		name: "French Polynesia",
		phoneCode: "+689",
		language: "French",
	},
	{
		code: "TF",
		name: "French Southern Territories",
		phoneCode: "+262",
		language: "French",
	},
	{ code: "GA", name: "Gabon", phoneCode: "+241", language: "French" },
	{ code: "GM", name: "Gambia", phoneCode: "+220", language: "English" },
	{ code: "GE", name: "Georgia", phoneCode: "+995", language: "Georgian" },
	{ code: "DE", name: "Germany", phoneCode: "+49", language: "German" },
	{ code: "GH", name: "Ghana", phoneCode: "+233", language: "English" },
	{ code: "GI", name: "Gibraltar", phoneCode: "+350", language: "English" },
	{ code: "GR", name: "Greece", phoneCode: "+30", language: "Greek" },
	{ code: "GL", name: "Greenland", phoneCode: "+299", language: "Greenlandic" },
	{ code: "GD", name: "Grenada", phoneCode: "+1-473", language: "English" },
	{ code: "GP", name: "Guadeloupe", phoneCode: "+590", language: "French" },
	{
		code: "GU",
		name: "Guam",
		phoneCode: "+1-671",
		language: "English, Chamorro",
	},
	{ code: "GT", name: "Guatemala", phoneCode: "+502", language: "Spanish" },
	{ code: "GG", name: "Guernsey", phoneCode: "+44", language: "English" },
	{ code: "GN", name: "Guinea", phoneCode: "+224", language: "French" },
	{
		code: "GW",
		name: "Guinea-Bissau",
		phoneCode: "+245",
		language: "Portuguese",
	},
	{ code: "GY", name: "Guyana", phoneCode: "+592", language: "English" },
	{
		code: "HT",
		name: "Haiti",
		phoneCode: "+509",
		language: "French, Haitian Creole",
	},
	{
		code: "HM",
		name: "Heard Island and McDonald Islands",
		phoneCode: "+672",
		language: "English",
	},
	{
		code: "VA",
		name: "Holy See (Vatican City State)",
		phoneCode: "+379",
		language: "Italian, Latin",
	},
	{ code: "HN", name: "Honduras", phoneCode: "+504", language: "Spanish" },
	{
		code: "HK",
		name: "Hong Kong",
		phoneCode: "+852",
		language: "Chinese, English",
	},
	{ code: "HU", name: "Hungary", phoneCode: "+36", language: "Hungarian" },
	{ code: "IS", name: "Iceland", phoneCode: "+354", language: "Icelandic" },
	{ code: "IN", name: "India", phoneCode: "+91", language: "Hindi, English" },
	{ code: "ID", name: "Indonesia", phoneCode: "+62", language: "Indonesian" },
	{
		code: "IR",
		name: "Iran, Islamic Republic of",
		phoneCode: "+98",
		language: "Persian",
	},
	{ code: "IQ", name: "Iraq", phoneCode: "+964", language: "Arabic, Kurdish" },
	{
		code: "IE",
		name: "Ireland",
		phoneCode: "+353",
		language: "Irish, English",
	},
	{ code: "IM", name: "Isle of Man", phoneCode: "+44", language: "English" },
	{ code: "IL", name: "Israel", phoneCode: "+972", language: "Hebrew, Arabic" },
	{ code: "IT", name: "Italy", phoneCode: "+39", language: "Italian" },
	{ code: "JM", name: "Jamaica", phoneCode: "+1-876", language: "English" },
	{ code: "JP", name: "Japan", phoneCode: "+81", language: "Japanese" },
	{ code: "JE", name: "Jersey", phoneCode: "+44", language: "English" },
	{ code: "JO", name: "Jordan", phoneCode: "+962", language: "Arabic" },
	{
		code: "KZ",
		name: "Kazakhstan",
		phoneCode: "+7",
		language: "Kazakh, Russian",
	},
	{
		code: "KE",
		name: "Kenya",
		phoneCode: "+254",
		language: "English, Swahili",
	},
	{
		code: "KI",
		name: "Kiribati",
		phoneCode: "+686",
		language: "English, Gilbertese",
	},
	{
		code: "KP",
		name: "Korea, Democratic People's Republic of",
		phoneCode: "+850",
		language: "Korean",
	},
	{
		code: "KR",
		name: "Korea, Republic of",
		phoneCode: "+82",
		language: "Korean",
	},
	{ code: "KW", name: "Kuwait", phoneCode: "+965", language: "Arabic" },
	{
		code: "KG",
		name: "Kyrgyzstan",
		phoneCode: "+996",
		language: "Kyrgyz, Russian",
	},
	{
		code: "LA",
		name: "Lao People's Democratic Republic",
		phoneCode: "+856",
		language: "Lao",
	},
	{ code: "LV", name: "Latvia", phoneCode: "+371", language: "Latvian" },
	{ code: "LB", name: "Lebanon", phoneCode: "+961", language: "Arabic" },
	{
		code: "LS",
		name: "Lesotho",
		phoneCode: "+266",
		language: "Sesotho, English",
	},
	{ code: "LR", name: "Liberia", phoneCode: "+231", language: "English" },
	{ code: "LY", name: "Libya", phoneCode: "+218", language: "Arabic" },
	{ code: "LI", name: "Liechtenstein", phoneCode: "+423", language: "German" },
	{ code: "LT", name: "Lithuania", phoneCode: "+370", language: "Lithuanian" },
	{
		code: "LU",
		name: "Luxembourg",
		phoneCode: "+352",
		language: "Luxembourgish, French, German",
	},
	{
		code: "MO",
		name: "Macao",
		phoneCode: "+853",
		language: "Chinese, Portuguese",
	},
	{
		code: "MG",
		name: "Madagascar",
		phoneCode: "+261",
		language: "Malagasy, French",
	},
	{
		code: "MW",
		name: "Malawi",
		phoneCode: "+265",
		language: "English, Chichewa",
	},
	{ code: "MY", name: "Malaysia", phoneCode: "+60", language: "Malay" },
	{ code: "MV", name: "Maldives", phoneCode: "+960", language: "Dhivehi" },
	{ code: "ML", name: "Mali", phoneCode: "+223", language: "French" },
	{
		code: "MT",
		name: "Malta",
		phoneCode: "+356",
		language: "Maltese, English",
	},
	{
		code: "MH",
		name: "Marshall Islands",
		phoneCode: "+692",
		language: "Marshallese, English",
	},
	{ code: "MQ", name: "Martinique", phoneCode: "+596", language: "French" },
	{ code: "MR", name: "Mauritania", phoneCode: "+222", language: "Arabic" },
	{
		code: "MU",
		name: "Mauritius",
		phoneCode: "+230",
		language: "English, French",
	},
	{ code: "YT", name: "Mayotte", phoneCode: "+262", language: "French" },
	{ code: "MX", name: "Mexico", phoneCode: "+52", language: "Spanish" },
	{
		code: "FM",
		name: "Micronesia, Federated States of",
		phoneCode: "+691",
		language: "English",
	},
	{
		code: "MD",
		name: "Moldova, Republic of",
		phoneCode: "+373",
		language: "Romanian",
	},
	{ code: "MC", name: "Monaco", phoneCode: "+377", language: "French" },
	{ code: "MN", name: "Mongolia", phoneCode: "+976", language: "Mongolian" },
	{
		code: "ME",
		name: "Montenegro",
		phoneCode: "+382",
		language: "Montenegrin",
	},
	{ code: "MS", name: "Montserrat", phoneCode: "+1-664", language: "English" },
	{
		code: "MA",
		name: "Morocco",
		phoneCode: "+212",
		language: "Arabic, Berber",
	},
	{ code: "MZ", name: "Mozambique", phoneCode: "+258", language: "Portuguese" },
	{ code: "MM", name: "Myanmar", phoneCode: "+95", language: "Burmese" },
	{ code: "NA", name: "Namibia", phoneCode: "+264", language: "English" },
	{
		code: "NR",
		name: "Nauru",
		phoneCode: "+674",
		language: "Nauruan, English",
	},
	{ code: "NP", name: "Nepal", phoneCode: "+977", language: "Nepali" },
	{ code: "NL", name: "Netherlands", phoneCode: "+31", language: "Dutch" },
	{ code: "NC", name: "New Caledonia", phoneCode: "+687", language: "French" },
	{
		code: "NZ",
		name: "New Zealand",
		phoneCode: "+64",
		language: "English, Māori",
	},
	{ code: "NI", name: "Nicaragua", phoneCode: "+505", language: "Spanish" },
	{ code: "NE", name: "Niger", phoneCode: "+227", language: "French" },
	{ code: "NG", name: "Nigeria", phoneCode: "+234", language: "English" },
	{ code: "NU", name: "Niue", phoneCode: "+683", language: "English, Niuean" },
	{
		code: "NF",
		name: "Norfolk Island",
		phoneCode: "+672",
		language: "English",
	},
	{
		code: "MK",
		name: "North Macedonia",
		phoneCode: "+389",
		language: "Macedonian",
	},
	{
		code: "MP",
		name: "Northern Mariana Islands",
		phoneCode: "+1-670",
		language: "English, Chamorro",
	},
	{ code: "NO", name: "Norway", phoneCode: "+47", language: "Norwegian" },
	{ code: "OM", name: "Oman", phoneCode: "+968", language: "Arabic" },
	{ code: "PK", name: "Pakistan", phoneCode: "+92", language: "Urdu, English" },
	{
		code: "PW",
		name: "Palau",
		phoneCode: "+680",
		language: "Palauan, English",
	},
	{
		code: "PS",
		name: "Palestine, State of",
		phoneCode: "+970",
		language: "Arabic",
	},
	{ code: "PA", name: "Panama", phoneCode: "+507", language: "Spanish" },
	{
		code: "PG",
		name: "Papua New Guinea",
		phoneCode: "+675",
		language: "English, Tok Pisin",
	},
	{
		code: "PY",
		name: "Paraguay",
		phoneCode: "+595",
		language: "Spanish, Guaraní",
	},
	{ code: "PE", name: "Peru", phoneCode: "+51", language: "Spanish, Quechua" },
	{
		code: "PH",
		name: "Philippines",
		phoneCode: "+63",
		language: "Filipino, English",
	},
	{ code: "PN", name: "Pitcairn", phoneCode: "+64", language: "English" },
	{ code: "PL", name: "Poland", phoneCode: "+48", language: "Polish" },
	{ code: "PT", name: "Portugal", phoneCode: "+351", language: "Portuguese" },
	{
		code: "PR",
		name: "Puerto Rico",
		phoneCode: "+1-787",
		language: "Spanish, English",
	},
	{ code: "QA", name: "Qatar", phoneCode: "+974", language: "Arabic" },
	{ code: "RO", name: "Romania", phoneCode: "+40", language: "Romanian" },
	{
		code: "RU",
		name: "Russian Federation",
		phoneCode: "+7",
		language: "Russian",
	},
	{
		code: "RW",
		name: "Rwanda",
		phoneCode: "+250",
		language: "Kinyarwanda, French, English",
	},
	{ code: "RE", name: "Réunion", phoneCode: "+262", language: "French" },
	{
		code: "BL",
		name: "Saint Barthélemy",
		phoneCode: "+590",
		language: "French",
	},
	{
		code: "SH",
		name: "Saint Helena, Ascension and Tristan da Cunha",
		phoneCode: "+290",
		language: "English",
	},
	{
		code: "KN",
		name: "Saint Kitts and Nevis",
		phoneCode: "+1-869",
		language: "English",
	},
	{ code: "LC", name: "Saint Lucia", phoneCode: "+1-758", language: "English" },
	{
		code: "MF",
		name: "Saint Martin (French part)",
		phoneCode: "+590",
		language: "French",
	},
	{
		code: "PM",
		name: "Saint Pierre and Miquelon",
		phoneCode: "+508",
		language: "French",
	},
	{
		code: "VC",
		name: "Saint Vincent and the Grenadines",
		phoneCode: "+1-784",
		language: "English",
	},
	{ code: "WS", name: "Samoa", phoneCode: "+685", language: "Samoan, English" },
	{ code: "SM", name: "San Marino", phoneCode: "+378", language: "Italian" },
	{
		code: "ST",
		name: "Sao Tome and Principe",
		phoneCode: "+239",
		language: "Portuguese",
	},
	{ code: "SA", name: "Saudi Arabia", phoneCode: "+966", language: "Arabic" },
	{ code: "SN", name: "Senegal", phoneCode: "+221", language: "French" },
	{ code: "RS", name: "Serbia", phoneCode: "+381", language: "Serbian" },
	{
		code: "SC",
		name: "Seychelles",
		phoneCode: "+248",
		language: "English, French, Seychellois Creole",
	},
	{ code: "SL", name: "Sierra Leone", phoneCode: "+232", language: "English" },
	{
		code: "SG",
		name: "Singapore",
		phoneCode: "+65",
		language: "English, Malay, Mandarin, Tamil",
	},
	{
		code: "SX",
		name: "Sint Maarten (Dutch part)",
		phoneCode: "+1-721",
		language: "Dutch, English",
	},
	{ code: "SK", name: "Slovakia", phoneCode: "+421", language: "Slovak" },
	{ code: "SI", name: "Slovenia", phoneCode: "+386", language: "Slovene" },
	{
		code: "SB",
		name: "Solomon Islands",
		phoneCode: "+677",
		language: "English",
	},
	{
		code: "SO",
		name: "Somalia",
		phoneCode: "+252",
		language: "Somali, Arabic",
	},
	{
		code: "ZA",
		name: "South Africa",
		phoneCode: "+27",
		language: "English, Afrikaans, Zulu, Xhosa",
	},
	{
		code: "GS",
		name: "South Georgia and the South Sandwich Islands",
		phoneCode: "+500",
		language: "English",
	},
	{ code: "SS", name: "South Sudan", phoneCode: "+211", language: "English" },
	{ code: "ES", name: "Spain", phoneCode: "+34", language: "Spanish" },
	{
		code: "LK",
		name: "Sri Lanka",
		phoneCode: "+94",
		language: "Sinhala, Tamil",
	},
	{ code: "SD", name: "Sudan", phoneCode: "+249", language: "Arabic, English" },
	{ code: "SR", name: "Suriname", phoneCode: "+597", language: "Dutch" },
	{
		code: "SJ",
		name: "Svalbard and Jan Mayen",
		phoneCode: "+47",
		language: "Norwegian",
	},
	{ code: "SE", name: "Sweden", phoneCode: "+46", language: "Swedish" },
	{
		code: "CH",
		name: "Switzerland",
		phoneCode: "+41",
		language: "German, French, Italian, Romansh",
	},
	{
		code: "SY",
		name: "Syrian Arab Republic",
		phoneCode: "+963",
		language: "Arabic",
	},
	{
		code: "TW",
		name: "Taiwan, Province of China",
		phoneCode: "+886",
		language: "Mandarin Chinese",
	},
	{ code: "TJ", name: "Tajikistan", phoneCode: "+992", language: "Tajik" },
	{
		code: "TZ",
		name: "Tanzania, United Republic of",
		phoneCode: "+255",
		language: "Swahili, English",
	},
	{ code: "TH", name: "Thailand", phoneCode: "+66", language: "Thai" },
	{
		code: "TL",
		name: "Timor-Leste",
		phoneCode: "+670",
		language: "Tetum, Portuguese",
	},
	{ code: "TG", name: "Togo", phoneCode: "+228", language: "French" },
	{
		code: "TK",
		name: "Tokelau",
		phoneCode: "+690",
		language: "English, Tokelauan",
	},
	{ code: "TO", name: "Tonga", phoneCode: "+676", language: "Tongan, English" },
	{
		code: "TT",
		name: "Trinidad and Tobago",
		phoneCode: "+1-868",
		language: "English",
	},
	{ code: "TN", name: "Tunisia", phoneCode: "+216", language: "Arabic" },
	{ code: "TR", name: "Turkey", phoneCode: "+90", language: "Turkish" },
	{ code: "TM", name: "Turkmenistan", phoneCode: "+993", language: "Turkmen" },
	{
		code: "TC",
		name: "Turks and Caicos Islands",
		phoneCode: "+1-649",
		language: "English",
	},
	{
		code: "TV",
		name: "Tuvalu",
		phoneCode: "+688",
		language: "Tuvaluan, English",
	},
	{
		code: "UG",
		name: "Uganda",
		phoneCode: "+256",
		language: "English, Swahili",
	},
	{ code: "UA", name: "Ukraine", phoneCode: "+380", language: "Ukrainian" },
	{
		code: "AE",
		name: "United Arab Emirates",
		phoneCode: "+971",
		language: "Arabic",
	},
	{ code: "GB", name: "United Kingdom", phoneCode: "+44", language: "English" },
	{ code: "US", name: "United States", phoneCode: "+1", language: "English" },
	{
		code: "UM",
		name: "United States Minor Outlying Islands",
		phoneCode: "+1",
		language: "English",
	},
	{ code: "UY", name: "Uruguay", phoneCode: "+598", language: "Spanish" },
	{ code: "UZ", name: "Uzbekistan", phoneCode: "+998", language: "Uzbek" },
	{
		code: "VU",
		name: "Vanuatu",
		phoneCode: "+678",
		language: "Bislama, English, French",
	},
	{
		code: "VE",
		name: "Venezuela, Bolivarian Republic of",
		phoneCode: "+58",
		language: "Spanish",
	},
	{ code: "VN", name: "Viet Nam", phoneCode: "+84", language: "Vietnamese" },
	{
		code: "VG",
		name: "Virgin Islands, British",
		phoneCode: "+1-284",
		language: "English",
	},
	{
		code: "VI",
		name: "Virgin Islands, U.S.",
		phoneCode: "+1-340",
		language: "English",
	},
	{
		code: "WF",
		name: "Wallis and Futuna",
		phoneCode: "+681",
		language: "French",
	},
	{ code: "EH", name: "Western Sahara", phoneCode: "+212", language: "Arabic" },
	{ code: "YE", name: "Yemen", phoneCode: "+967", language: "Arabic" },
	{ code: "ZM", name: "Zambia", phoneCode: "+260", language: "English" },
	{
		code: "ZW",
		name: "Zimbabwe",
		phoneCode: "+263",
		language: "English, Shona, Ndebele",
	},
	{ code: "AX", name: "Åland Islands", phoneCode: "+358", language: "Swedish" },
] as const;
